[package]
name = "sqrt"
version = "0.1.0"
edition = "2021"

[dependencies]
plotters = "0.3.3"

[profile.release]
lto = true

[[bin]]
name = "sqrt-bin"
path = "src/sqrt_exapl.rs"

[[bin]]
name = "empty-app"
path = "src/dummy.rs"

