apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqrt-deployment
  labels:
    app: sqrt-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sqrt-app
  template:
    metadata:
      labels:
        app: sqrt-app
    spec:
      containers:
      - name: sqrt-bin-container
        image: us-west2-docker.pkg.dev/psychic-karma-401718/main/sqrt-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sqrt-service
spec:
  selector:
    app: sqrt-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000